import {
	Company,
	Vehicle,
	Wagon,
	Product,
	Warehouse,
	InventoryItem,
	VehicleCargoItem,
	SiteVisit,
	SiteOperation,
	SystemService,
	TariffRule,
	Invoice,
	Payment,
	CustomerAccountSummary,
	DashboardStats,
	AuditLog,
	SystemNotification,
	User,
} from '@/lib/types/logistics'

// ==================== کاربران دمو ====================
export const MOCK_USERS: User[] = [
	{
		id: 'u1',
		username: 'superadmin',
		fullName: 'مهندس محمودی (مدیر ارشد)',
		role: 'super_admin',
		phone: '09121111111',
		email: 'admin@logistics-platform.ir',
		isActive: true,
		createdAt: '1404/01/01',
	},
	{
		id: 'u2',
		username: 'tech_admin',
		fullName: 'علی رضایی (مدیر فنی)',
		role: 'admin',
		phone: '09122222222',
		email: 'rezaei@logistics-platform.ir',
		isActive: true,
		createdAt: '1404/02/15',
	},
	{
		id: 'u3',
		username: 'manager1',
		fullName: 'سارا حسینی (مدیر بازرگانی)',
		role: 'manager',
		phone: '09123333333',
		email: 'hoseini@logistics-platform.ir',
		isActive: true,
		createdAt: '1404/03/10',
	},
	{
		id: 'u4',
		username: 'op_site',
		fullName: 'حسین احمدی (اپراتور شیفت صبح)',
		role: 'operator',
		phone: '09124444444',
		isActive: true,
		createdAt: '1404/04/01',
	},
]

// ==================== ۲۱ خدمت استاندارد سامانه ====================
export const MOCK_SERVICES: SystemService[] = [
	{
		id: 'srv_1',
		code: 'SRV-01',
		name: 'ترانشیپمنت لیفتراکی',
		category: 'transshipment',
		unit: 'per_operation',
		unitTitleFa: 'هر عملیات',
		basePriceRial: 45000000,
		description: 'انتقال بار با لیفتراک بین وسایل نقلیه یا سکو به صورت مقطوع',
		isActive: true,
	},
	{
		id: 'srv_2',
		code: 'SRV-02',
		name: 'ترانشیپمنت سواری به کامیون',
		category: 'transshipment',
		unit: 'per_vehicle',
		unitTitleFa: 'هر دستگاه',
		basePriceRial: 25000000,
		description: 'بارگیری یا تخلیه خودروی سواری به/از کامیون خودروبر',
		isActive: true,
	},
	{
		id: 'srv_3',
		code: 'SRV-03',
		name: 'ترانشیپمنت کامیون به کامیون',
		category: 'transshipment',
		unit: 'per_ton',
		unitTitleFa: 'هر تن',
		basePriceRial: 850000,
		description: 'تخلیه و بارگیری مستقیم بار از یک کامیون به کامیون دیگر',
		isActive: true,
	},
	{
		id: 'srv_4',
		code: 'SRV-04',
		name: 'دیماند و خدمات اولیه ورود',
		category: 'traffic',
		unit: 'fixed',
		unitTitleFa: 'مقطوع',
		basePriceRial: 15000000,
		description: 'هزینه آماده‌سازی و پذیرش بار',
		isActive: true,
	},
	{
		id: 'srv_5',
		code: 'SRV-05',
		name: 'حق ورود تریلی',
		category: 'traffic',
		unit: 'per_vehicle',
		unitTitleFa: 'هر دستگاه',
		basePriceRial: 5000000,
		description: 'تعرفه ورود تریلی سنگین به محوطه سکو',
		isActive: true,
	},
	{
		id: 'srv_6',
		code: 'SRV-06',
		name: 'حمل‌ونقل لیفتراک (ساعتی/روزانه)',
		category: 'equipment',
		unit: 'per_day',
		unitTitleFa: 'هر روز',
		basePriceRial: 60000000,
		description: 'اجاره و به‌کارگیری روزانه لیفتراک به همراه راننده',
		isActive: true,
	},
	{
		id: 'srv_7',
		code: 'SRV-07',
		name: 'ورود واگن',
		category: 'rail',
		unit: 'per_wagon',
		unitTitleFa: 'هر واگن',
		basePriceRial: 35000000,
		description: 'هزینه پذیرش و ورود هر واگن باری به شبکه ریلی سکو',
		isActive: true,
	},
	{
		id: 'srv_8',
		code: 'SRV-08',
		name: 'شب‌خواب واگن',
		category: 'rail',
		unit: 'per_day',
		unitTitleFa: 'هر شب/واگن',
		basePriceRial: 12000000,
		description: 'هزینه توقف شبانه واگن در خطوط توقف',
		isActive: true,
	},
	{
		id: 'srv_9',
		code: 'SRV-09',
		name: 'شب‌خواب تریلی',
		category: 'traffic',
		unit: 'per_day',
		unitTitleFa: 'هر شب/دستگاه',
		basePriceRial: 3000000,
		description: 'هزینه توقف شبانه تریلی در پارکینگ لجستیکی',
		isActive: true,
	},
	{
		id: 'srv_10',
		code: 'SRV-10',
		name: 'شب‌خواب سواری',
		category: 'traffic',
		unit: 'per_day',
		unitTitleFa: 'هر شب/دستگاه',
		basePriceRial: 1500000,
		description: 'هزینه نگهداری و توقف خودروی سواری در پارکینگ',
		isActive: true,
	},
	{
		id: 'srv_11',
		code: 'SRV-11',
		name: 'انبارداری (سالن و محوطه)',
		category: 'storage',
		unit: 'per_hour',
		unitTitleFa: 'هر تن/ساعت',
		basePriceRial: 25000,
		description: 'نگهداری کالا در انبار سرپوشیده یا محوطه باز',
		isActive: true,
	},
	{
		id: 'srv_12',
		code: 'SRV-12',
		name: 'بیمه کالا و انبار',
		category: 'insurance',
		unit: 'per_day',
		unitTitleFa: 'روزانه بر ارزش',
		basePriceRial: 1500000,
		description: 'پوشش بیمه آتش‌سوزی، سرقت و خسارت کالا',
		isActive: true,
	},
	{
		id: 'srv_13',
		code: 'SRV-13',
		name: 'شب‌خواب کالا در بارانداز',
		category: 'storage',
		unit: 'per_day',
		unitTitleFa: 'هر تن/شب',
		basePriceRial: 450000,
		description: 'توقف کالا روی سکو یا بارانداز خارج از انبار اصلی',
		isActive: true,
	},
	{
		id: 'srv_14',
		code: 'SRV-14',
		name: 'حمل و جابجایی کالای خطرناک',
		category: 'special',
		unit: 'per_ton',
		unitTitleFa: 'هر تن',
		basePriceRial: 1800000,
		description: 'جابجایی محموله‌های شیمیایی، قابل اشتعال و ویژه',
		isActive: true,
	},
	{
		id: 'srv_15',
		code: 'SRV-15',
		name: 'مانور اضافه واگن',
		category: 'rail',
		unit: 'per_wagon',
		unitTitleFa: 'هر مانور/واگن',
		basePriceRial: 8000000,
		description: 'جابجایی و چیدمان اضافه واگن‌ها روی خطوط مانوری',
		isActive: true,
	},
	{
		id: 'srv_16',
		code: 'SRV-16',
		name: 'تخلیه لیفتراکی',
		category: 'equipment',
		unit: 'per_ton',
		unitTitleFa: 'هر تن',
		basePriceRial: 650000,
		description: 'تخلیه بارهای پالت شده یا بسته‌بندی شده توسط لیفتراک',
		isActive: true,
	},
	{
		id: 'srv_17',
		code: 'SRV-17',
		name: 'بارگیری لیفتراکی',
		category: 'equipment',
		unit: 'per_ton',
		unitTitleFa: 'هر تن',
		basePriceRial: 650000,
		description: 'بارگیری پالت‌ها بر روی وسیله نقلیه با لیفتراک',
		isActive: true,
	},
	{
		id: 'srv_18',
		code: 'SRV-18',
		name: 'تخلیه جرثقیلی',
		category: 'equipment',
		unit: 'per_ton',
		unitTitleFa: 'هر تن',
		basePriceRial: 950000,
		description: 'تخلیه محموله‌های سنگین، لوله، شمش یا کانتینر با جرثقیل',
		isActive: true,
	},
	{
		id: 'srv_19',
		code: 'SRV-19',
		name: 'بارگیری جرثقیلی',
		category: 'equipment',
		unit: 'per_ton',
		unitTitleFa: 'هر تن',
		basePriceRial: 950000,
		description: 'بارگیری محموله‌های فوق سنگین با جرثقیل',
		isActive: true,
	},
	{
		id: 'srv_20',
		code: 'SRV-20',
		name: 'ورود ماشین خارجی (ترانزیت)',
		category: 'traffic',
		unit: 'per_vehicle',
		unitTitleFa: 'هر دستگاه',
		basePriceRial: 8000000,
		description: 'هزینه بازرسی و ورود خودروهای حامل پلاک بین‌المللی',
		isActive: true,
	},
	{
		id: 'srv_21',
		code: 'SRV-21',
		name: 'ورود ماشین ایرانی',
		category: 'traffic',
		unit: 'per_vehicle',
		unitTitleFa: 'هر دستگاه',
		basePriceRial: 4000000,
		description: 'تعرفه پذیرش خودروهای تجاری داخلی',
		isActive: true,
	},
]

// ==================== شرکت‌ها و قراردادها ====================
export const MOCK_COMPANIES: Company[] = [
	{
		id: 'comp_1',
		name: 'شرکت لجستیک و ترانزیت خاورمیانه',
		nationalId: '10103456789',
		economicCode: '411356789123',
		registrationNumber: '445210',
		phone: '021-88997766',
		address: 'تهران، خیابان شهید بهشتی، پلاک ۱۲۴، طبقه ۴',
		type: 'legal',
		isActive: true,
		totalBalance: 345000000, // بدهکار
		description: 'بزرگترین مشتری ترانشیپمنت غلات و فلزات',
		createdAt: '1403/10/12',
		contacts: [
			{
				id: 'cnt_1',
				companyId: 'comp_1',
				fullName: 'مهندس کاظمی',
				position: 'مدیر لجستیک',
				mobile: '09121234567',
				email: 'kazemi@me-logistics.ir',
				isMainContact: true,
				isFinancialContact: false,
				isOperationalContact: true,
				receiveInvoices: false,
			},
			{
				id: 'cnt_2',
				companyId: 'comp_1',
				fullName: 'خانم شمس',
				position: 'مدیر امور مالی',
				mobile: '09129876543',
				email: 'shams@me-logistics.ir',
				isMainContact: false,
				isFinancialContact: true,
				isOperationalContact: false,
				receiveInvoices: true,
			},
		],
		contracts: [
			{
				id: 'cntr_1',
				contractNumber: 'CTR-1405-089',
				companyId: 'comp_1',
				companyName: 'شرکت لجستیک و ترانزیت خاورمیانه',
				startDate: '1405/01/01',
				endDate: '1405/12/29',
				status: 'active',
				discountPercentage: 15,
				freeServices: ['srv_4'], // دیماند رایگان
				specialTerms: 'تخفیف ۱۵ درصدی روی کلیه خدمات تخلیه و بارگیری لیفتراکی',
				description: 'قرارداد سالانه طلایی',
				createdAt: '1404/12/20',
			},
		],
	},
	{
		id: 'comp_2',
		name: 'مجتمع فولاد البرز کاسپین',
		nationalId: '10861234567',
		economicCode: '411789456123',
		registrationNumber: '320145',
		phone: '021-22446688',
		address: 'قزوین، شهرک صنعتی کاسپین، فاز ۲، بلوار پژوهش',
		type: 'legal',
		isActive: true,
		totalBalance: 820000000,
		description: 'تردد واگنی بالا، بارگیری و تخلیه شمش و ورق آهن',
		createdAt: '1403/08/01',
		contacts: [
			{
				id: 'cnt_3',
				companyId: 'comp_2',
				fullName: 'مهندس بهرامی',
				position: 'سرپرست ترابری ریلی',
				mobile: '09125556677',
				email: 'bahrami@caspiansteel.com',
				isMainContact: true,
				isFinancialContact: true,
				isOperationalContact: true,
				receiveInvoices: true,
			},
		],
		contracts: [
			{
				id: 'cntr_2',
				contractNumber: 'CTR-1405-042',
				companyId: 'comp_2',
				companyName: 'مجتمع فولاد البرز کاسپین',
				startDate: '1405/02/01',
				endDate: '1405/08/01',
				status: 'active',
				discountPercentage: 10,
				freeServices: [],
				specialTerms: 'نرخ ترجیحی جرثقیل و مانور ریلی',
				createdAt: '1405/01/25',
			},
		],
	},
	{
		id: 'comp_3',
		name: 'بازرگانی خودرو پارس سپهر',
		nationalId: '10320098765',
		phone: '021-77889900',
		address: 'تهران، کیلومتر ۱۴ جاده مخصوص کرج',
		type: 'legal',
		isActive: true,
		totalBalance: -45000000, // بستانکار
		description: 'ترانشیپمنت و دپوی خودروهای سواری وارداتی',
		createdAt: '1404/02/10',
		contacts: [
			{
				id: 'cnt_4',
				companyId: 'comp_3',
				fullName: 'آقای رستمی',
				position: 'مدیر بازرگانی',
				mobile: '09124443322',
				isMainContact: true,
				isFinancialContact: true,
				isOperationalContact: false,
				receiveInvoices: true,
			},
		],
		contracts: [],
	},
	{
		id: 'comp_4',
		name: 'صنایع پتروشیمی زاگرس آریا',
		nationalId: '10780045612',
		phone: '077-37295000',
		address: 'عسلویه، منطقه ویژه اقتصادی انرژی پارس',
		type: 'legal',
		isActive: true,
		totalBalance: 0,
		description: 'محموله‌های گرانول و مواد شیمیایی خطرناک در مخازن',
		createdAt: '1404/05/20',
		contacts: [
			{
				id: 'cnt_5',
				companyId: 'comp_4',
				fullName: 'دکتر صادقی',
				position: 'معاونت زنجیره تأمین',
				mobile: '09171112233',
				isMainContact: true,
				isFinancialContact: false,
				isOperationalContact: true,
				receiveInvoices: false,
			},
		],
		contracts: [],
	},
]

// ==================== خودروها ====================
export const MOCK_VEHICLES: Vehicle[] = [
	{
		id: 'veh_1',
		plateNumber: '۱۲ ع ۳۴۵ ایران ۲۲',
		driverName: 'مرتضی اکبری',
		driverPhone: '09129871122',
		companyId: 'comp_1',
		companyName: 'شرکت لجستیک و ترانزیت خاورمیانه',
		type: 'trailer',
		capacityTon: 25,
		country: 'ایران',
		isInsideSite: true,
		createdAt: '1404/11/01',
	},
	{
		id: 'veh_2',
		plateNumber: '۷۸ ج ۸۹۱ ایران ۱۱',
		driverName: 'سهراب گودرزی',
		driverPhone: '09193334455',
		companyId: 'comp_1',
		companyName: 'شرکت لجستیک و ترانزیت خاورمیانه',
		type: 'truck',
		capacityTon: 15,
		country: 'ایران',
		isInsideSite: true,
		createdAt: '1404/11/15',
	},
	{
		id: 'veh_3',
		plateNumber: '99-A-741 TR (ترکیه)',
		driverName: 'محمت اصلان',
		driverPhone: '+905321234567',
		companyId: 'comp_3',
		companyName: 'بازرگانی خودرو پارس سپهر',
		type: 'foreign',
		capacityTon: 22,
		country: 'ترکیه',
		isInsideSite: true,
		createdAt: '1405/01/10',
	},
	{
		id: 'veh_4',
		plateNumber: '۳۳ د ۶۵۴ ایران ۵۵',
		driverName: 'جواد کریمی',
		driverPhone: '09138889900',
		companyId: 'comp_2',
		companyName: 'مجتمع فولاد البرز کاسپین',
		type: 'trailer',
		capacityTon: 28,
		country: 'ایران',
		isInsideSite: false,
		createdAt: '1404/09/20',
	},
]

// ==================== واگن‌ها ====================
export const MOCK_WAGONS: Wagon[] = [
	{
		id: 'wgn_1',
		wagonNumber: 'WGN-880412',
		type: 'flat',
		companyId: 'comp_2',
		companyName: 'مجتمع فولاد البرز کاسپین',
		capacityTon: 60,
		cargoName: 'شمش فولادی ۵SP',
		status: 'loading',
		entryDate: '1405/06/02',
		entryTime: '08:30',
		isOvernight: true,
		maneuverCount: 2,
		trackNumber: 'خط ۴ ریلی - سکوی الف',
	},
	{
		id: 'wgn_2',
		wagonNumber: 'WGN-990145',
		type: 'covered',
		companyId: 'comp_1',
		companyName: 'شرکت لجستیک و ترانزیت خاورمیانه',
		capacityTon: 55,
		cargoName: 'کیسه‌های گندم و جو',
		status: 'unloading',
		entryDate: '1405/06/03',
		entryTime: '11:15',
		isOvernight: false,
		maneuverCount: 1,
		trackNumber: 'خط ۲ ریلی - انبار غلات',
	},
	{
		id: 'wgn_3',
		wagonNumber: 'WGN-774512',
		type: 'tanker',
		companyId: 'comp_4',
		companyName: 'صنایع پتروشیمی زاگرس آریا',
		capacityTon: 50,
		cargoName: 'متانول مایع',
		status: 'overnight',
		entryDate: '1405/06/01',
		entryTime: '16:00',
		isOvernight: true,
		maneuverCount: 3,
		trackNumber: 'خط ۵ توقف و مخازن',
	},
	{
		id: 'wgn_4',
		wagonNumber: 'WGN-662301',
		type: 'bordered',
		companyId: 'comp_2',
		companyName: 'مجتمع فولاد البرز کاسپین',
		capacityTon: 65,
		cargoName: 'سنگ آهن و ضایعات فلزی',
		status: 'arrived',
		entryDate: '1405/06/04',
		entryTime: '10:00',
		isOvernight: false,
		maneuverCount: 1,
		trackNumber: 'خط ۳ تخلیه مواد معدنی',
	},
]

// ==================== انبارها ====================
export const MOCK_WAREHOUSES: Warehouse[] = [
	{
		id: 'wh_1',
		name: 'انبار مرکزی سرپوشیده شماره ۱',
		code: 'WH-01',
		type: 'indoor_hall',
		totalCapacityTon: 15000,
		usedCapacityTon: 9450,
		managerName: 'مهندس حیدری',
		isActive: true,
		locations: [
			{ id: 'loc_1', warehouseId: 'wh_1', code: 'A-01', title: 'بخش غلات و پالت', capacityTon: 5000, currentOccupiedTon: 3200 },
			{ id: 'loc_2', warehouseId: 'wh_1', code: 'A-02', title: 'بخش تجهیزات صنعتی', capacityTon: 5000, currentOccupiedTon: 3800 },
			{ id: 'loc_3', warehouseId: 'wh_1', code: 'A-03', title: 'بخش بسته‌بندی ویژه', capacityTon: 5000, currentOccupiedTon: 2450 },
		],
	},
	{
		id: 'wh_2',
		name: 'محوطه باز دپوی فلزات و کانتینر',
		code: 'WH-02',
		type: 'open_yard',
		totalCapacityTon: 40000,
		usedCapacityTon: 26800,
		managerName: 'مهندس نوروزی',
		isActive: true,
		locations: [
			{ id: 'loc_4', warehouseId: 'wh_2', code: 'Y-01', title: 'دپوی شمش و میلگرد', capacityTon: 20000, currentOccupiedTon: 15000 },
			{ id: 'loc_5', warehouseId: 'wh_2', code: 'Y-02', title: 'محوطه استقرار کانتینر', capacityTon: 20000, currentOccupiedTon: 11800 },
		],
	},
	{
		id: 'wh_3',
		name: 'انبار کالاهای ویژه و خطرناک',
		code: 'WH-03',
		type: 'silo',
		totalCapacityTon: 8000,
		usedCapacityTon: 3100,
		managerName: 'دکتر صبوری',
		isActive: true,
		locations: [
			{ id: 'loc_6', warehouseId: 'wh_3', code: 'HAZ-01', title: 'مخازن مایعات شیمیایی', capacityTon: 4000, currentOccupiedTon: 1900 },
			{ id: 'loc_7', warehouseId: 'wh_3', code: 'HAZ-02', title: 'سالن ایزوله ضدحریق', capacityTon: 4000, currentOccupiedTon: 1200 },
		],
	},
]

// ==================== خودروهای موجود در انبار (با شماره شاسی یونیک) ====================
export const MOCK_VEHICLE_CARGO_ITEMS: VehicleCargoItem[] = [
	{
		id: 'v_item_1',
		chassisNumber: 'JTMHU01J8N4109882',
		brandAndModel: 'تویوتا لندکروزر GR Sport',
		modelYear: 2024,
		color: 'سفید صدفی متالیک',
		valueUsd: 85000,
		companyId: 'comp_3',
		companyName: 'بازرگانی خودرو پارس سپهر',
		batchCode: 'BATCH-405-CAR-01',
		warehouseName: 'پارکینگ خودروهای وارداتی',
		locationCode: 'PARK-A-12',
		entryDate: '1405/06/03',
		status: 'in_stock',
		notes: 'ترخیص موقت - بدون خط و خش',
	},
	{
		id: 'v_item_2',
		chassisNumber: 'JTMHU01J8N4109883',
		brandAndModel: 'تویوتا لندکروزر GR Sport',
		modelYear: 2024,
		color: 'مشکی متالیک',
		valueUsd: 85000,
		companyId: 'comp_3',
		companyName: 'بازرگانی خودرو پارس سپهر',
		batchCode: 'BATCH-405-CAR-01',
		warehouseName: 'پارکینگ خودروهای وارداتی',
		locationCode: 'PARK-A-13',
		entryDate: '1405/06/03',
		status: 'in_stock',
	},
	{
		id: 'v_item_3',
		chassisNumber: 'KM8RNDHF3PU712390',
		brandAndModel: 'هیوندای سانتافه Calligraphy AWD',
		modelYear: 2025,
		color: 'مشکی متالیک',
		valueUsd: 48000,
		companyId: 'comp_3',
		companyName: 'بازرگانی خودرو پارس سپهر',
		batchCode: 'BATCH-405-CAR-02',
		warehouseName: 'پارکینگ خودروهای وارداتی',
		locationCode: 'PARK-B-04',
		entryDate: '1405/06/04',
		status: 'in_stock',
	},
	{
		id: 'v_item_4',
		chassisNumber: 'KM8RNDHF3PU712391',
		brandAndModel: 'هیوندای سانتافه Calligraphy AWD',
		modelYear: 2025,
		color: 'سربی / خاکستری تیره',
		valueUsd: 48000,
		companyId: 'comp_3',
		companyName: 'بازرگانی خودرو پارس سپهر',
		batchCode: 'BATCH-405-CAR-02',
		warehouseName: 'پارکینگ خودروهای وارداتی',
		locationCode: 'PARK-B-05',
		entryDate: '1405/06/04',
		status: 'in_stock',
	},
	{
		id: 'v_item_5',
		chassisNumber: 'WBA53AH07PFP10944',
		brandAndModel: 'بی‌ام‌و سری ۵ سدان 530i',
		modelYear: 2024,
		color: 'آبی متالیک کاربنی',
		valueUsd: 72000,
		companyId: 'comp_3',
		companyName: 'بازرگانی خودرو پارس سپهر',
		batchCode: 'BATCH-405-CAR-03',
		warehouseName: 'پارکینگ خودروهای وارداتی',
		locationCode: 'PARK-C-01',
		entryDate: '1405/05/29',
		status: 'in_stock',
	},
]

// ==================== کالاها ====================
export const MOCK_PRODUCTS: Product[] = [
	{
		id: 'prod_1',
		code: 'PRD-1001',
		name: 'شمش فولادی بیلت 150*150',
		categoryId: 'cat_steel',
		categoryName: 'فلزات و فولاد',
		companyId: 'comp_2',
		companyName: 'مجتمع فولاد البرز کاسپین',
		unit: 'ton',
		storageType: 'normal',
		hazardNature: 'heavy',
		isDangerous: false,
		isHeavy: true,
		isValuable: true,
		estimatedValueRial: 280000000, // هر تن
		currentStockTotal: 15000,
	},
	{
		id: 'prod_2',
		code: 'PRD-1002',
		name: 'گندم درجه یک دامی (کیسه‌ای)',
		categoryId: 'cat_grain',
		categoryName: 'غلات و کشاورزی',
		companyId: 'comp_1',
		companyName: 'شرکت لجستیک و ترانزیت خاورمیانه',
		unit: 'ton',
		storageType: 'normal',
		hazardNature: 'normal',
		isDangerous: false,
		isHeavy: false,
		isValuable: false,
		estimatedValueRial: 180000000,
		currentStockTotal: 3200,
	},
	{
		id: 'prod_3',
		code: 'PRD-1003',
		name: 'گرانول پلی‌اتیلن ترفتالات سنگین (PET)',
		categoryId: 'cat_chem',
		categoryName: 'پتروشیمی و پلیمری',
		companyId: 'comp_4',
		companyName: 'صنایع پتروشیمی زاگرس آریا',
		unit: 'ton',
		storageType: 'dangerous',
		hazardNature: 'dangerous',
		isDangerous: true,
		isHeavy: false,
		isValuable: true,
		estimatedValueRial: 650000000,
		currentStockTotal: 1900,
	},
	{
		id: 'prod_4',
		code: 'PRD-1004',
		name: 'تویوتا لندکروزر GR Sport 2024',
		categoryId: 'cat_auto',
		categoryName: 'ماشین',
		companyId: 'comp_3',
		companyName: 'بازرگانی خودرو پارس سپهر',
		unit: 'device',
		storageType: 'valuable',
		hazardNature: 'valuable',
		isDangerous: false,
		isHeavy: false,
		isValuable: true,
		estimatedValueRial: 65000000000,
		currentStockTotal: 12,
		vehicleSpecs: {
			chassisNumber: 'JTMHU01J8N4109882',
			brandAndModel: 'Toyota Land Cruiser GR Sport',
			modelYear: 2024,
			color: 'سفید صدفی متالیک',
			valueUsd: 85000,
		},
	},
	{
		id: 'prod_5',
		code: 'PRD-1005',
		name: 'هیوندای سانتافه Calligraphy 2025',
		categoryId: 'cat_auto',
		categoryName: 'ماشین',
		companyId: 'comp_3',
		companyName: 'بازرگانی خودرو پارس سپهر',
		unit: 'device',
		storageType: 'valuable',
		hazardNature: 'valuable',
		isDangerous: false,
		isHeavy: false,
		isValuable: true,
		estimatedValueRial: 38000000000,
		currentStockTotal: 18,
		vehicleSpecs: {
			chassisNumber: 'KM8RNDHF3PU712390',
			brandAndModel: 'Hyundai Santa Fe Calligraphy AWD',
			modelYear: 2025,
			color: 'مشکی متالیک',
			valueUsd: 48000,
		},
	},
]

// ==================== گردش موجودی انبار ====================
export const MOCK_INVENTORY_ITEMS: InventoryItem[] = [
	{
		id: 'inv_1',
		batchCode: 'BATCH-405-881',
		productId: 'prod_1',
		productName: 'شمش فولادی بیلت 150*150',
		productCode: 'PRD-1001',
		companyId: 'comp_2',
		companyName: 'مجتمع فولاد البرز کاسپین',
		warehouseId: 'wh_2',
		warehouseName: 'محوطه باز دپوی فلزات و کانتینر',
		locationCode: 'Y-01',
		quantity: 15000,
		unit: 'تن',
		tonnage: 15000,
		isDangerous: false,
		isValuable: true,
		entryDateTime: '1405/05/20',
		storageDays: 15,
		accumulatedStorageCost: 135000000,
		accumulatedInsuranceCost: 22500000,
	},
	{
		id: 'inv_2',
		batchCode: 'BATCH-405-902',
		productId: 'prod_2',
		productName: 'گندم درجه یک دامی (کیسه‌ای)',
		productCode: 'PRD-1002',
		companyId: 'comp_1',
		companyName: 'شرکت لجستیک و ترانزیت خاورمیانه',
		warehouseId: 'wh_1',
		warehouseName: 'انبار مرکزی سرپوشیده شماره ۱',
		locationCode: 'A-01',
		quantity: 3200,
		unit: 'تن',
		tonnage: 3200,
		isDangerous: false,
		isValuable: false,
		entryDateTime: '1405/05/28',
		storageDays: 7,
		accumulatedStorageCost: 33600000,
		accumulatedInsuranceCost: 10500000,
	},
	{
		id: 'inv_3',
		batchCode: 'BATCH-405-915',
		productId: 'prod_3',
		productName: 'گرانول پلی‌اتیلن ترفتالات سنگین (PET)',
		productCode: 'PRD-1003',
		companyId: 'comp_4',
		companyName: 'صنایع پتروشیمی زاگرس آریا',
		warehouseId: 'wh_3',
		warehouseName: 'انبار کالاهای ویژه و خطرناک',
		locationCode: 'HAZ-01',
		quantity: 1900,
		unit: 'تن',
		tonnage: 1900,
		isDangerous: true,
		isValuable: true,
		entryDateTime: '1405/05/15',
		storageDays: 20,
		accumulatedStorageCost: 48000000,
		accumulatedInsuranceCost: 30000000,
	},
]

// ==================== ورود و خروج سایت (Site Visits) ====================
export const MOCK_SITE_VISITS: SiteVisit[] = [
	{
		id: 'vis_1',
		trackingCode: 'VIS-405-01',
		targetType: 'vehicle',
		vehiclePlate: '۱۲ ع ۳۴۵ ایران ۲۲',
		driverName: 'مرتضی اکبری',
		driverPhone: '09129871122',
		companyId: 'comp_1',
		companyName: 'شرکت لجستیک و ترانزیت خاورمیانه',
		entryDateTime: '1405/06/04 07:30',
		operationType: 'transshipment',
		parkingLocation: 'سکوی شماره ۲ بارانداز',
		entranceFeeCalculated: 5000000,
		overnightFeeCalculated: 0,
		status: 'inside',
		notes: 'محموله گندم وارداتی جهت ترانشیپ به واگن',
	},
	{
		id: 'vis_2',
		trackingCode: 'VIS-405-02',
		targetType: 'vehicle',
		vehiclePlate: '99-A-741 TR',
		driverName: 'محمت اصلان',
		driverPhone: '+905321234567',
		companyId: 'comp_3',
		companyName: 'بازرگانی خودرو پارس سپهر',
		entryDateTime: '1405/06/03 14:20',
		operationType: 'unloading',
		parkingLocation: 'پارکینگ خودروهای وارداتی',
		entranceFeeCalculated: 8000000,
		overnightFeeCalculated: 3000000,
		status: 'inside',
		notes: 'تریلی خودروبر حامل ۸ دستگاه سواری',
	},
	{
		id: 'vis_3',
		trackingCode: 'VIS-405-03',
		targetType: 'wagon',
		wagonNumber: 'WGN-880412',
		companyId: 'comp_2',
		companyName: 'مجتمع فولاد البرز کاسپین',
		entryDateTime: '1405/06/02 08:30',
		operationType: 'loading',
		parkingLocation: 'خط ۴ ریلی - سکوی الف',
		entranceFeeCalculated: 35000000,
		overnightFeeCalculated: 24000000,
		status: 'inside',
		notes: 'بارگیری ۶۰ تن شمش فولادی با جرثقیل',
	},
	{
		id: 'vis_4',
		trackingCode: 'VIS-405-04',
		targetType: 'vehicle',
		vehiclePlate: '۳۳ د ۶۵۴ ایران ۵۵',
		driverName: 'جواد کریمی',
		driverPhone: '09138889900',
		companyId: 'comp_2',
		companyName: 'مجتمع فولاد البرز کاسپین',
		entryDateTime: '1405/06/03 09:00',
		exitDateTime: '1405/06/03 16:45',
		stayDurationMinutes: 465,
		operationType: 'loading',
		parkingLocation: 'سکوی بارگیری انبار ۲',
		entranceFeeCalculated: 5000000,
		overnightFeeCalculated: 0,
		status: 'exited',
	},
]

// ==================== عملیات در حال اجرا و انجام شده سایت ====================
export const MOCK_OPERATIONS: SiteOperation[] = [
	{
		id: 'op_1',
		operationCode: 'OP-405-101',
		type: 'transshipment',
		companyId: 'comp_1',
		companyName: 'شرکت لجستیک و ترانزیت خاورمیانه',
		vehiclePlate: '۱۲ ع ۳۴۵ ایران ۲۲',
		wagonNumber: 'WGN-990145',
		productId: 'prod_2',
		productName: 'گندم درجه یک دامی (کیسه‌ای)',
		tonnage: 24,
		route: 'truck_to_wagon',
		equipmentType: 'forklift',
		equipmentId: 'لیفتراک شماره ۳ کوماتسو',
		operatorName: 'حسین احمدی',
		startDateTime: '1405/06/04 08:15',
		unitPrice: 850000,
		totalCalculatedCost: 20400000,
		status: 'in_progress',
		notes: 'تخلیه از تریلی و بارگیری مستقیم داخل واگن مسقف',
	},
	{
		id: 'op_2',
		operationCode: 'OP-405-102',
		type: 'loading_crane',
		companyId: 'comp_2',
		companyName: 'مجتمع فولاد البرز کاسپین',
		wagonNumber: 'WGN-880412',
		productId: 'prod_1',
		productName: 'شمش فولادی بیلت 150*150',
		tonnage: 60,
		equipmentType: 'crane',
		equipmentId: 'جرثقیل دروازه‌ای ۴۰ تن سکوی ریلی',
		operatorName: 'اصغر مرادی',
		startDateTime: '1405/06/04 09:00',
		unitPrice: 950000,
		totalCalculatedCost: 57000000,
		status: 'in_progress',
		notes: 'بارگیری شمش فولادی با رعایت استانداردهای ریلی',
	},
	{
		id: 'op_3',
		operationCode: 'OP-405-103',
		type: 'transshipment',
		companyId: 'comp_3',
		companyName: 'بازرگانی خودرو پارس سپهر',
		vehiclePlate: '99-A-741 TR',
		productId: 'prod_4',
		productName: 'خودرو سواری شاسی‌بلند وارداتی صفر',
		tonnage: 16,
		quantity: 8,
		route: 'truck_to_platform',
		operatorName: 'حسین احمدی',
		startDateTime: '1405/06/03 15:00',
		endDateTime: '1405/06/03 17:30',
		durationHours: 2.5,
		unitPrice: 25000000,
		totalCalculatedCost: 200000000,
		status: 'completed',
		notes: 'تخلیه ۸ دستگاه خودرو و هدایت به پارکینگ موقت',
	},
]

// ==================== تعرفه‌های اختصاصی ====================
export const MOCK_TARIFF_RULES: TariffRule[] = [
	{
		id: 'tr_1',
		serviceId: 'srv_16',
		serviceName: 'تخلیه لیفتراکی',
		companyId: 'comp_1',
		discountPercent: 15,
		multiplier: 0.85,
		isFree: false,
		validFrom: '1405/01/01',
		validTo: '1405/12/29',
		version: 1,
	},
	{
		id: 'tr_2',
		serviceId: 'srv_4',
		serviceName: 'دیماند و خدمات اولیه ورود',
		companyId: 'comp_1',
		isFree: true,
		validFrom: '1405/01/01',
		validTo: '1405/12/29',
		version: 1,
	},
	{
		id: 'tr_3',
		serviceId: 'srv_18',
		serviceName: 'تخلیه جرثقیلی',
		companyId: 'comp_2',
		customRateRial: 800000, // بجای 950,000
		isFree: false,
		validFrom: '1405/02/01',
		validTo: '1405/08/01',
		version: 1,
	},
]

// ==================== فاکتورها ====================
export const MOCK_INVOICES: Invoice[] = [
	{
		id: 'invc_1',
		invoiceNumber: 'INV-1405-0081',
		companyId: 'comp_1',
		companyName: 'شرکت لجستیک و ترانزیت خاورمیانه',
		companyNationalId: '10103456789',
		contractId: 'cntr_1',
		periodStart: '1405/05/01',
		periodEnd: '1405/05/31',
		issuedDate: '1405/06/01',
		dueDate: '1405/06/15',
		status: 'issued',
		items: [
			{
				id: 'ii_1',
				serviceId: 'srv_1',
				serviceName: 'ترانشیپمنت لیفتراکی',
				dateTime: '1405/05/10',
				quantity: 4,
				unitTitle: 'عملیات',
				unitPrice: 45000000,
				discountAmount: 27000000, // 15% discount
				insuranceAmount: 5000000,
				taxAmount: 15800000,
				finalTotal: 173800000,
			},
			{
				id: 'ii_2',
				serviceId: 'srv_11',
				serviceName: 'انبارداری غلات (انبار ۱)',
				dateTime: '1405/05/31',
				quantity: 3200,
				unitTitle: 'تن/ساعت',
				unitPrice: 25000,
				discountAmount: 0,
				insuranceAmount: 8000000,
				taxAmount: 8800000,
				finalTotal: 96800000,
			},
			{
				id: 'ii_3',
				serviceId: 'srv_5',
				serviceName: 'حق ورود تریلی (۱۵ دستگاه)',
				dateTime: '1405/05/25',
				quantity: 15,
				unitTitle: 'دستگاه',
				unitPrice: 5000000,
				discountAmount: 0,
				insuranceAmount: 0,
				taxAmount: 7500000,
				finalTotal: 82500000,
			},
		],
		subtotalAmount: 335000000,
		totalDiscount: 27000000,
		totalInsurance: 13000000,
		totalTax: 32100000,
		finalPayableAmount: 353100000,
		paidAmount: 8100000,
		remainingAmount: 345000000,
		notes: 'فاکتور خدمات تجمیعی مرداد ماه ۱۴۰۵',
	},
	{
		id: 'invc_2',
		invoiceNumber: 'INV-1405-0078',
		companyId: 'comp_2',
		companyName: 'مجتمع فولاد البرز کاسپین',
		companyNationalId: '10861234567',
		contractId: 'cntr_2',
		periodStart: '1405/05/01',
		periodEnd: '1405/05/31',
		issuedDate: '1405/06/01',
		dueDate: '1405/06/10',
		status: 'issued',
		items: [
			{
				id: 'ii_4',
				serviceId: 'srv_7',
				serviceName: 'ورود واگن و مانور ریلی',
				dateTime: '1405/05/18',
				quantity: 12,
				unitTitle: 'واگن',
				unitPrice: 35000000,
				discountAmount: 42000000,
				insuranceAmount: 15000000,
				taxAmount: 39300000,
				finalTotal: 432300000,
			},
			{
				id: 'ii_5',
				serviceId: 'srv_18',
				serviceName: 'تخلیه جرثقیلی شمش فولادی',
				dateTime: '1405/05/20',
				quantity: 500,
				unitTitle: 'تن',
				unitPrice: 800000,
				discountAmount: 0,
				insuranceAmount: 20000000,
				taxAmount: 42000000,
				finalTotal: 462000000,
			},
		],
		subtotalAmount: 820000000,
		totalDiscount: 42000000,
		totalInsurance: 35000000,
		totalTax: 81300000,
		finalPayableAmount: 894300000,
		paidAmount: 74300000,
		remainingAmount: 820000000,
	},
]

// ==================== پرداخت‌ها ====================
export const MOCK_PAYMENTS: Payment[] = [
	{
		id: 'pay_1',
		receiptNumber: 'PAY-1405-901',
		invoiceId: 'invc_1',
		invoiceNumber: 'INV-1405-0081',
		companyId: 'comp_1',
		companyName: 'شرکت لجستیک و ترانزیت خاورمیانه',
		amountRial: 8100000,
		paymentMethod: 'bank_transfer',
		paymentDate: '1405/06/02',
		bankName: 'بانک ملت',
		trackingCode: 'TR-998822110',
		isVerified: true,
		recordedBy: 'خانم شمس',
		notes: 'پیش‌پرداخت بابت فاکتور مرداد',
	},
	{
		id: 'pay_2',
		receiptNumber: 'PAY-1405-880',
		invoiceId: 'invc_2',
		invoiceNumber: 'INV-1405-0078',
		companyId: 'comp_2',
		companyName: 'مجتمع فولاد البرز کاسپین',
		amountRial: 74300000,
		paymentMethod: 'cheque',
		paymentDate: '1405/06/01',
		chequeNumber: 'CHQ-55443322',
		chequeDueDate: '1405/06/25',
		isVerified: true,
		recordedBy: 'مهندس بهرامی',
	},
]

// ==================== شاخص‌های داشبورد ====================
export const MOCK_DASHBOARD_STATS: DashboardStats = {
	todayRevenueRial: 77400000,
	monthRevenueRial: 1247400000,
	activeCompaniesCount: 4,
	vehiclesInsideSite: 3,
	wagonsInsideSite: 3,
	totalInventoryTon: 20100,
	warehouseCapacityPercentage: 62.5,
	unpaidInvoicesCount: 2,
	totalOutstandingDebtRial: 1165000000,
	todayOperationsCount: 8,
}

// ==================== لاگ سیستم ====================
export const MOCK_AUDIT_LOGS: AuditLog[] = [
	{
		id: 'log_1',
		userId: 'u4',
		userName: 'حسین احمدی (اپراتور)',
		userRole: 'operator',
		action: 'create',
		entityType: 'operation',
		entityId: 'OP-405-101',
		details: 'ثبت عملیات ترانشیپمنت ۲۴ تن گندم از تریلی به واگن WGN-990145',
		ipAddress: '192.168.1.45',
		timestamp: '1405/06/04 08:15',
	},
	{
		id: 'log_2',
		userId: 'u4',
		userName: 'حسین احمدی (اپراتور)',
		userRole: 'operator',
		action: 'create',
		entityType: 'vehicle',
		entityId: 'VIS-405-01',
		details: 'ثبت ورود تریلی ۱۲ ع ۳۴۵ ایران ۲۲ متعلق به شرکت لجستیک خاورمیانه',
		ipAddress: '192.168.1.45',
		timestamp: '1405/06/04 07:30',
	},
	{
		id: 'log_3',
		userId: 'u1',
		userName: 'مهندس محمودی (سوپر ادمین)',
		userRole: 'super_admin',
		action: 'create',
		entityType: 'invoice',
		entityId: 'INV-1405-0081',
		details: 'صدور فاکتور تجمیعی مرداد ماه برای شرکت لجستیک و ترانزیت خاورمیانه به مبلغ ۳۵۳،۱۰۰،۰۰۰ ریال',
		ipAddress: '192.168.1.10',
		timestamp: '1405/06/01 10:00',
	},
]

// ==================== اعلان‌ها ====================
export const MOCK_NOTIFICATIONS: SystemNotification[] = [
	{
		id: 'notif_1',
		title: 'ماندگاری واگن بیش از حد مجاز',
		message: 'واگن WGN-880412 بیش از ۴۸ ساعت در خط ۴ ریلی متوقف بوده و مشمول هزینه شب‌خواب است.',
		type: 'warning',
		isRead: false,
		createdAt: '۱۰ دقیقه پیش',
		link: '/fleet/wagons',
	},
	{
		id: 'notif_2',
		title: 'سررسید فاکتور معوق',
		message: 'سررسید فاکتور شماره INV-1405-0078 مجتمع فولاد البرز کاسپین نزدیک است.',
		type: 'info',
		isRead: false,
		createdAt: '۲ ساعت پیش',
		link: '/invoices',
	},
	{
		id: 'notif_3',
		title: 'تکمیل ظرفیت سالن ایزوله خطرناک',
		message: 'ظرفیت سالن ایزوله ضدحریق به ۷۵ درصد رسیده است.',
		type: 'error',
		isRead: true,
		createdAt: 'دیروز',
		link: '/warehouses',
	},
]
